spring.datasource.url=jdbc:postgresql://localhost:5432/production_management
spring.datasource.username=postgres
spring.datasource.password=rootroot
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true